In [1]:
import numpy as np

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [12]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [27]:
a4 = np.array([[[[1,2,3],
              [4,5,6],
              [7,8,9]],
              [[1,2,3],
              [4,5,6],
              [7,8,9]]],
              [[[1,2,3],
              [4,5,6],
              [7,8,9]]]]
             )

<ipython-input-27-de1b36f4e4fc>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  a4 = np.array([[[[1,2,3],


In [28]:
a4.shape

(2,)

In [30]:
import numpy as np    

a = np.arange(72)

a = np.reshape(a, (4,3,2,3))

In [31]:
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41]],

        [[42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65]],

        [[66, 67, 68],
         [69, 70, 71]]]])

In [32]:
a1.shape

(3,)

In [33]:
a1.size

3

In [39]:
random_array = np.random.randint(0,10,size=(3,5,4))
random_array


array([[[1, 3, 3, 0],
        [5, 5, 9, 6],
        [5, 1, 6, 7],
        [5, 7, 3, 7],
        [3, 5, 8, 3]],

       [[0, 2, 5, 9],
        [0, 8, 4, 1],
        [1, 2, 2, 0],
        [8, 9, 0, 3],
        [3, 3, 5, 2]],

       [[9, 0, 8, 2],
        [6, 6, 0, 7],
        [7, 8, 1, 1],
        [3, 7, 1, 2],
        [6, 3, 7, 2]]])

In [40]:
## Random array of  (n,n) shape between 0 and 1
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.17658253, 0.26778332, 0.0298872 ],
       [0.90012861, 0.75494661, 0.87709146],
       [0.97691498, 0.76955948, 0.40405939],
       [0.13829761, 0.10197679, 0.11562622],
       [0.85858399, 0.84642091, 0.77999876]])

In [42]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.00341101, 0.04225232, 0.23463067],
       [0.27044204, 0.82123694, 0.16312714],
       [0.93917793, 0.04536159, 0.91884428],
       [0.02280626, 0.82985919, 0.40569675],
       [0.24031456, 0.42433983, 0.88600705]])

In [ ]:
! git add Numpy_intro.ipynb
! git commit -m "20:43/29-06-2021"
! git push origin main